databases:
  - name: VeGaMusic
    ipAllowList: []
    region: Virginia
    plan: free
services:
  - type: web
    plan: free
    name: VeGaMusic
    env: python
    buildCommand: pip install -U -r VeGaMenTs.txt
    startCommand: python3 -m VeGaMusic
    region: Virginia
    envVars:
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: VeGaMusic
          property: connectionString   
    autoDeploy: false
